pollSystemTurkcell/Models/Poll.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace pollSystemTurkcell.Models
{
    public class Poll
    {
        public int ID { get; set; }

        [Display(Name = "Anket Başlığı ")]
        public string Title { get; set; }

        [Display(Name = "Anket Detayları ")]
        public string Details { get; set; }

        [Display(Name = "Anket İçin Gereken Onay Sayısı ")]
        public int NoOfConfirmations { get; set; }

        [Display(Name = "Anket Kapanış Tarihi ")]
        public DateTime Deadline { get; set; }

        [Display(Name = "Anket Oluşturulma Tarihi ")]
        public DateTime CreationDate { get; set; }

        [Display(Name = "Anketi Oluşturan Admin")]
        public int CreatorID { get; set; }
       
        [Display(Name = "Anketi Oluşturan Admin")]
        public User Creator { get; set; }

        [Display(Name = "Anket Soruları")]
        public IList<Question> Questions { get; set; }
        public IList<PollUser> User { get; set; }
        public IList<PollResponse> PollResponses { get; set; }

    }
}

pollSystemTurkcell/Controllers/PollsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using pollSystemTurkcell.Models;
using pollSystemTurkcell.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Threading;
using System.IO;
using NPOI.XWPF.UserModel;

namespace pollSystemTurkcell.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PollsController : Controller
    {
        private IPollService pollService;
        private IUserService userService;
        private IQuestionService questionService;
        private IPollUserService pollUserService;
        private IPollResponseService pollResponseService;

        public PollsController(IPollService pollService, IUserService userService, IQuestionService questionService, IPollUserService pollUserService, IPollResponseService pollResponseService)
        {
            this.pollService = pollService;
            this.userService = userService;
            this.questionService = questionService;
            this.pollUserService = pollUserService;
            this.pollResponseService = pollResponseService;
        }
        public IActionResult Index()
        {
            var polls = pollService.GetPolls().OrderByDescending(q => q.CreationDate); //Lists all existing polls
           
            return View(polls);
        }

        public IActionResult Create()
        {
            int creatorID = userService.GetIDByUsername(User.Identity.Name);
            ViewBag.CreatorID = creatorID;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Poll poll)
        {
            if (ModelState.IsValid) //If there are no errors; create the poll and return to the list
            {
                pollService.CreatePoll(poll);
                int pollID = poll.ID;
                return RedirectToAction("Details", "Polls", new { pollID });
            }

            return View(); //If there is an error open the same view again
        }
        //TODO 6: Deadline tarihinin geçmiş olmasını önleyemedim

        public IActionResult Delete(int pollID)
        {
            var poll = pollService.GetPollByID(pollID);

            if (poll == null)
            {
                return NotFound();
            }

            return View(poll);
        }

        [HttpPost]
        public IActionResult Delete(Poll poll)
        {

            pollService.DeletePoll(poll);
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Edit(int pollID)
        {
            var poll = pollService.GetPollByID(pollID);
            ViewBag.CreationDate = poll.CreationDate;
            ViewBag.CreatorID = poll.CreatorID;
            if (poll == null)
            {
                return NotFound();
            }

            return View(poll);
        }

        [HttpPost]
        public IActionResult Edit(Poll poll)
        {
            if (ModelState.IsValid)
            {
                pollService.UpdatePoll(poll);
                return RedirectToAction(nameof(Index));
            }

            return View(poll);
        }

        public IActionResult Details(int pollID)
        {
            var poll = pollService.GetPollByID(pollID);
           
            IEnumerable<Question> questions = questionService.GetQuestionsByPollID(pollID);
            ViewBag.Questions = questions;

            ViewBag.NoOfAnswers = pollUserService.NoOfPeopleAnswered(pollID);

            if (poll == null)
            {
                return NotFound();
            }

            return View(poll);
        }

       

        public IActionResult DownloadList(string AnswerDetails, int pollID)
        {
           var poll = pollService.GetPollByID(pollID);
           pollResponseService.CreateList(poll);

            return View(poll); ;
        }
    }
}

pollSystemTurkcell/Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using pollSystemTurkcell.Models;
using pollSystemTurkcell.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pollSystemTurkcell.Controllers
{
    public class QuestionsController : Controller
    {
        private IPollService pollService;
        private IQuestionService questionService;

        public QuestionsController(IPollService pollService, IQuestionService questionService)
        {
            this.pollService = pollService;
            this.questionService = questionService;
        }

        public IActionResult Create(int pollID)
        {
            ViewBag.PollName = pollService.GetPollByID(pollID).Title;
            ViewBag.PollID = pollID; 
            return View();
        }

        [HttpPost]
        public IActionResult Create(Question question)
        {

            if (ModelState.IsValid)
            {
                questionService.Add(question);
                return RedirectToAction("Details", "Polls", new { question.PollID });

            }


            return View();

        }

        public IActionResult Delete(int qID)
        {
            var question = questionService.GetQuestionByID(qID);
            ViewBag.PollName = pollService.GetPollByID(question.PollID).Title;

            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        [HttpPost]
        public IActionResult Delete(Question question)
        {

            questionService.DeleteQuestion(question);
            return RedirectToAction("Details", "Polls", new { question.PollID });

        }

        public IActionResult Edit(int qID)
        {
            var question = questionService.GetQuestionByID(qID);
            ViewBag.PollName = pollService.GetPollByID(question.PollID).Title;
           
            if (question == null)
            {
                return NotFound();
            }

            return View(question);
        }

        [HttpPost]
        public IActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                questionService.UpdateQuestion(question);
                return RedirectToAction("Details", "Polls", new { question.PollID });
            }

            return View(question);
        }
    }
}

pollSystemTurkcell/Views/Polls/Create.cshtml
@model pollSystemTurkcell.Models.Poll

@{
    ViewData["Title"] = "Create";
    DateTime now = DateTime.Now;
    string dateNow = now.ToUniversalTime().ToString("u");

}

<h1>Yeni Anket Ekle</h1>

<h4>Anket Bilgileri</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoOfConfirmations" class="control-label"></label>
                <input asp-for="NoOfConfirmations" class="form-control" />
                <span asp-validation-for="NoOfConfirmations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input type="date" asp-for="Deadline" min="@dateNow" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="@Model.CreationDate" value="@DateTime.Now" />
            <input type="hidden" asp-for="@Model.CreatorID" value="@ViewBag.CreatorID" />
            <div class="form-group">
                <input type="submit" value="Ekle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye Dön</a>
</div>

pollSystemTurkcell/Views/Polls/Delete.cshtml
@model pollSystemTurkcell.Models.Poll

@{
    ViewData["Title"] = "Delete";
}

<h1>Sil</h1>

<h3>Bu anketi silmek istediğinize emin misiniz?</h3>
<p><em>Bu işlem geri alınamaz.</em></p>
<div>
    <h4>Anket</h4>
    <hr />
    <dl class="row">      
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatorID)
        </dt>
        <dd class = "col-sm-10">
            @Model.Creator.Name
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.ID" />
        <input type="submit" value="Sil" class="btn btn-danger" /> |
        <a asp-action="Index">Listeye Dön</a>
    </form>
</div>

pollSystemTurkcell/Views/Polls/Details.cshtml
@model pollSystemTurkcell.Models.Poll

@{
    ViewData["Title"] = "Details";
}

<h1>Anket Detayları</h1>

<div>
    <h4>Anket</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NoOfConfirmations)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NoOfConfirmations)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Deadline)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreationDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreationDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatorID)
        </dt>
        <dd class="col-sm-10">
            @Model.Creator.Name
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Questions)
        </dt>
        <dd class="col-sm-10">
            @foreach (var item in ViewBag.Questions)
            {
                <p>@item.Text</p>
                <a type="button" asp-action="Delete" asp-controller="Questions" asp-route-qID="@item.ID" class="btn btn-danger justify-content-center" method="post">Soruyu Sil</a>
                <a type="button" asp-action="Edit" asp-controller="Questions" asp-route-qID="@item.ID" class="btn btn-success justify-content-center" method="post">Soruyu Düzenle</a>
                <p>   </p>

            }
            <p>   </p>
            <a type="button" asp-action="Create" asp-controller="Questions" asp-route-pollID="@Model.ID" class="btn btn-info" method="post">Ankete Soru Ekle</a>
        </dd>
        <dt class="col-sm-2">
            Cevaplayanların Sayısı
        </dt>
        <dd class="col-sm-10">
            @ViewBag.NoOfAnswers
            <a type="button" asp-action="AnswerDetails" asp-controller="PollReply" asp-route-pollID="@Model.ID" class="btn btn-outline-info justify-content-center">Cevap Ayrıntılarını Gör</a>
        </dd>
    </dl>
</div>
<div>
    <a type="button" class="btn btn-warning" asp-action="Edit" asp-route-pollID="@Model.ID"> Düzenle</a> |
    <a asp-action="Index">Listeye Dön</a>
</div>

pollSystemTurkcell/Views/Polls/DownloadList.cshtml
@model Poll
@{
    ViewData["Title"] = "DownloadList";
}

<h1>@Model.Title Anketi</h1>


<div class="alert alert-info" role="alert">
    <strong>Tebrikler! </strong> Listeniz indirildi. <a asp-action="Index" class="alert-link"> Anket listesine dönmek için tıkla </a>
</div>

pollSystemTurkcell/Views/Polls/Edit.cshtml
@model pollSystemTurkcell.Models.Poll

@{
    ViewData["Title"] = "Edit";
}

<h1>Düzenle</h1>

<h4>Anket Bilgileri</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="@Model.ID" />
            <input type="hidden" asp-for="@Model.CreationDate" value="@ViewBag.CreationDate" />
            <input type="hidden" asp-for="@Model.CreatorID" value="@ViewBag.CreatorID" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Details" class="control-label"></label>
                <input asp-for="Details" class="form-control" />
                <span asp-validation-for="Details" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoOfConfirmations" class="control-label"></label>
                <input asp-for="NoOfConfirmations" class="form-control" />
                <span asp-validation-for="NoOfConfirmations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Listeye Dön</a>
</div>

pollSystemTurkcell/Views/Polls/Index.cshtml
@model IEnumerable<pollSystemTurkcell.Models.Poll>

@{
    ViewData["Title"] = "Index";
}

<h1>Anketler</h1>

<p>
    <a asp-action="Create">Yeni Anket Ekle</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreationDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Creator)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deadline)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Creator.Name)
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { pollID = item.ID }) |
                @Html.ActionLink("Detaylar", "Details", new { pollID = item.ID }) |
                @Html.ActionLink("Sil", "Delete", new { pollID = item.ID })
            </td>
        </tr>
}
    </tbody>
</table>